In [ ]:
%pip install pandas numpy matplotlib seaborn scikit-learn

Collecting pandas
  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/10/72/06aefff8fe5efc5e1ca8bfb2695b648a435358f6dc224d4e40159314181a/pandas-3.1.0-cp312-cp312-win_amd64.whl.metadata
  Downloading pandas-3.1.0-cp312-cp312-win_amd64.whl.metadata (18 kB)
Collecting numpy
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/12/33/fefe62073dc8acfd0f2b9ed7c003af2f50aa61555e113e6db02b8f79f145/numpy-2.5.4-cp312-cp312-win_amd64.whl.metadata
  Downloading numpy-2.5.4-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Collecting matplotlib
  Obtaining dependency information for matplotlib from https://files.pythonhosted.org/packages/04/93/0d239bde12b308262265c2d98909b2f0ecad2b5deeae96241642e822e9c7/matplotlib-3.11.2-cp312-cp312-win_amd64.whl.metadata
  Downloading matplotlib-3.11.2-cp312-cp312-win_amd64.whl.metadata (80 kB)
     ---------------------------------------- 0.0/80.3 kB ? eta -:--:--
     ----- ---------------------------------- 10.2/80.3 kB ? eta -:--:--
     ------------------- ------------------ 41.0/80.3 kB 991.0 kB/s eta 0:00:01
     --------------------------------- ---- 71.7/80.3 kB 991.0 kB/s eta 0:00:01
     -------------------------------------- 80.3/80.3 kB 752.9 kB/s eta 0:00:00
Collecting seaborn
  Obtaining dependency information for seaborn from https://files.pythonhosted.org/packages/83/11/00d3c3dfc25ad54e731d91449895a79e4bf2384dc3ac01809010ba88f6d5/seaborn-0.13.2-py3-none-any.whl.metadata
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting scikit-learn
  Obtaining dependency information for scikit-learn from https://files.pythonhosted.org/packages/72/8d/27c054166bac671770d1ea0ef7716134fe8119c0df224a58c89fd735a61c/scikit_learn-1.9.1-cp312-cp312-win_amd64.whl.metadata
  Downloading scikit_learn-1.9.1-cp312-cp312-win_amd64.whl.metadata (9.3 kB)
Requirement already satisfied: python-dateutil>=2.9.0 in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from pandas) (3.0.0)
Requirement already satisfied: tzdata in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from pandas) (2026.6)
Collecting contourpy>=1.0.1 (from matplotlib)
  Obtaining dependency information for contourpy>=1.0.1 from https://files.pythonhosted.org/packages/50/a9/dab08786bb4d77ef9a046b3c1be923be4e73c5d07d91f5a54e8ea9b09e41/contourpy-1.4.0-cp312-cp312-win_amd64.whl.metadata
  Using cached contourpy-1.4.0-cp312-cp312-win_amd64.whl.metadata (3.8 kB)
Collecting cycler>=0.10 (from matplotlib)
  Obtaining dependency information for cycler>=0.10 from https://files.pythonhosted.org/packages/e7/05/c19819d5e3d95294a6f5947fb9b9629efb316b96de511b418c53d245aae6/cycler-0.12.1-py3-none-any.whl.metadata
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.28.2 (from matplotlib)
  Obtaining dependency information for fonttools>=4.28.2 from https://files.pythonhosted.org/packages/1c/3e/ef786310a3774ae7aacaa288ca6d1e1dfd03c24214137478e4b630b76af0/fonttools-4.68.0-cp312-cp312-win_amd64.whl.metadata
  Downloading fonttools-4.68.0-cp312-cp312-win_amd64.whl.metadata (142 kB)
     ---------------------------------------- 0.0/142.6 kB ? eta -:--:--
     ------------------------- ------------- 92.2/142.6 kB 2.6 MB/s eta 0:00:01
     ----------------------------------- -- 133.1/142.6 kB 2.0 MB/s eta 0:00:01
     -------------------------------------- 142.6/142.6 kB 1.4 MB/s eta 0:00:00
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Obtaining dependency information for kiwisolver>=1.3.1 from https://files.pythonhosted.org/packages/6e/7c/7b210498f9f92e1cd7855f260fa69ef056881087b199ee20c208f0e4189a/kiwisolver-1.5.1-cp312-cp312-win_amd64.whl.metadata
  Using cached kiwisolver-1.5.1-cp312-cp312-win_amd64.whl.metadata (5.2 kB)
Requirement already satisfied: packaging>=20.0 in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from matplotlib) (26.3)
Collecting pillow>=9 (from matplotlib)
  Obtaining dependency information for pillow>=9 from https://files.pythonhosted.org/packages/ff/cd/73a79ecdc822076002eb24b5e1e4a530b0bb5310fcb6d239abbec877110b/pillow-13.0.0-cp312-cp312-win_amd64.whl.metadata
  Downloading pillow-13.0.0-cp312-cp312-win_amd64.whl.metadata (9.3 kB)
Collecting pyparsing>=3 (from matplotlib)
  Obtaining dependency information for pyparsing>=3 from https://files.pythonhosted.org/packages/38/bb/d215ee7c73b61497b28a5503f9f53523f294fcc936762b7caf90e0c1c2b5/pyparsing-3.3.3-py3-none-any.whl.metadata
  Using cached pyparsing-3.3.3-py3-none-any.whl.metadata (5.9 kB)
Collecting scipy>=1.10.0 (from scikit-learn)
  Obtaining dependency information for scipy>=1.10.0 from https://files.pythonhosted.org/packages/39/e7/979fd14e75008623df31ba70d6bb144700f68feadcea042021c06a05bf82/scipy-1.18.1-cp312-cp312-win_amd64.whl.metadata
  Downloading scipy-1.18.1-cp312-cp312-win_amd64.whl.metadata (61 kB)
     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     ---------------------------------------- 61.2/61.2 kB 3.2 MB/s eta 0:00:00
Collecting joblib>=1.4.0 (from scikit-learn)
  Obtaining dependency information for joblib>=1.4.0 from https://files.pythonhosted.org/packages/18/53/84099323c2ec4be98d935f63c033ac4151ee83836ca1050ede3b3aadf155/joblib-1.6.0-py3-none-any.whl.metadata
  Downloading joblib-1.6.0-py3-none-any.whl.metadata (6.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Obtaining dependency information for narwhals>=2.0.1 from https://files.pythonhosted.org/packages/cf/82/8ef9c7e0f50493307a49c09cfa7f00c5a778b6d1921f7b2dabe1d3a5809e/narwhals-2.28.0-py3-none-any.whl.metadata
  Downloading narwhals-2.28.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Obtaining dependency information for threadpoolctl>=3.5.0 from https://files.pythonhosted.org/packages/43/3f/f88a53f60a472b46f4023f56d204dd7de33d34c5d2acbfa0d70a674e639e/threadpoolctl-3.7.0-py3-none-any.whl.metadata
  Using cached threadpoolctl-3.7.0-py3-none-any.whl.metadata (24 kB)
Collecting cloudpickle>=3.0 (from joblib>=1.4.0->scikit-learn)
  Obtaining dependency information for cloudpickle>=3.0 from https://files.pythonhosted.org/packages/88/39/799be3f2f0f38cc727ee3b4f1445fe6d5e4133064ec2e4115069418a5bb6/cloudpickle-3.1.2-py3-none-any.whl.metadata
  Using cached cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: six>=1.6 in c:\users\lenovo\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.9.0->pandas) (1.17.0)
Downloading pandas-3.1.0-cp312-cp312-win_amd64.whl (10.7 MB)
   ---------------------------------------- 0.0/10.7 MB ? eta -:--:--
   ---------------------------------------- 0.1/10.7 MB 1.7 MB/s eta 0:00:07
    --------------------------------------- 0.2/10.7 MB 2.2 MB/s eta 0:00:05
   - -------------------------------------- 0.3/10.7 MB 2.6 MB/s eta 0:00:04
   - -------------------------------------- 0.5/10.7 MB 2.6 MB/s eta 0:00:05
   - -------------------------------------- 0.5/10.7 MB 2.6 MB/s eta 0:00:04
   -- ------------------------------------- 0.6/10.7 MB 2.5 MB/s eta 0:00:05
   -- ------------------------------------- 0.7/10.7 MB 2.4 MB/s eta 0:00:05
   --- ------------------------------------ 0.9/10.7 MB 2.7 MB/s eta 0:00:04
   ---- ----------------------------------- 1.1/10.7 MB 2.9 MB/s eta 0:00:04
   ---- ----------------------------------- 1.3/10.7 MB 3.0 MB/s eta 0:00:04
   ----- ---------------------------------- 1.5/10.7 MB 3.2 MB/s eta 0:00:03
   ------ --------------------------------- 1.7/10.7 MB 3.1 MB/s eta 0:00:03
   ------- -------------------------------- 1.9/10.7 MB 3.3 MB/s eta 0:00:03
   ------- -------------------------------- 2.1/10.7 MB 3.4 MB/s eta 0:00:03
   -------- ------------------------------- 2.2/10.7 MB 3.5 MB/s eta 0:00:03
   --------- ------------------------------ 2.5/10.7 MB 3.6 MB/s eta 0:00:03
   --------- ------------------------------ 2.7/10.7 MB 3.6 MB/s eta 0:00:03
   ---------- ----------------------------- 2.9/10.7 MB 3.7 MB/s eta 0:00:03
   ----------- ---------------------------- 3.0/10.7 MB 3.6 MB/s eta 0:00:03
   ----------- ---------------------------- 3.2/10.7 MB 3.6 MB/s eta 0:00:03
   ------------ --------------------------- 3.2/10.7 MB 3.6 MB/s eta 0:00:03
   ------------ --------------------------- 3.3/10.7 MB 3.6 MB/s eta 0:00:03
   ------------ --------------------------- 3.5/10.7 MB 3.5 MB/s eta 0:00:03
   ------------- -------------------------- 3.6/10.7 MB 3.5 MB/s eta 0:00:03
   -------------- ------------------------- 3.8/10.7 MB 3.5 MB/s eta 0:00:02
   -------------- ------------------------- 4.0/10.7 MB 3.6 MB/s eta 0:00:02
   --------------- ------------------------ 4.2/10.7 MB 3.6 MB/s eta 0:00:02
   ---------------- ----------------------- 4.4/10.7 MB 3.6 MB/s eta 0:00:02
   ---------------- ----------------------- 4.5/10.7 MB 3.6 MB/s eta 0:00:02
   ----------------- ---------------------- 4.7/10.7 MB 3.7 MB/s eta 0:00:02
   ------------------ --------------------- 5.0/10.7 MB 3.7 MB/s eta 0:00:02
   ------------------- -------------------- 5.2/10.7 MB 3.7 MB/s eta 0:00:02
   -------------------- ------------------- 5.4/10.7 MB 3.8 MB/s eta 0:00:02
   -------------------- ------------------- 5.6/10.7 MB 3.8 MB/s eta 0:00:02
   --------------------- ------------------ 5.8/10.7 MB 3.8 MB/s eta 0:00:02
   ---------------------- ----------------- 6.0/10.7 MB 3.8 MB/s eta 0:00:02
   ---------------------- ----------------- 6.1/10.7 MB 3.8 MB/s eta 0:00:02
   ----------------------- ---------------- 6.2/10.7 MB 3.8 MB/s eta 0:00:02
   ----------------------- ---------------- 6.4/10.7 MB 3.8 MB/s eta 0:00:02
   ------------------------ --------------- 6.6/10.7 MB 3.9 MB/s eta 0:00:02
   ------------------------- -------------- 6.9/10.7 MB 3.8 MB/s eta 0:00:02
   -------------------------- ------------- 7.1/10.7 MB 3.9 MB/s eta 0:00:01
   --------------------------- ------------ 7.3/10.7 MB 3.9 MB/s eta 0:00:01
   --------------------------- ------------ 7.4/10.7 MB 3.9 MB/s eta 0:00:01
   ---------------------------- ----------- 7.6/10.7 MB 3.9 MB/s eta 0:00:01
   ----------------------------- ---------- 7.8/10.7 MB 3.9 MB/s eta 0:00:01
   ----------------------------- ---------- 8.0/10.7 MB 3.9 MB/s eta 0:00:01
   ------------------------------ --------- 8.2/10.7 MB 3.9 MB/s eta 0:00:01
   ------------------------------ --------- 8.3/10.7 MB 3.9 MB/s eta 0:00:01
   ------------------------------- -------- 8.5/10.7 MB 3.9 MB/s eta 0:00:01
   -------------------------------- ------- 8.7/10.7 MB 3.9 MB/s eta 0:00:01
   --------------------------------- ------ 8.9/10.7 MB 3.9 MB/s eta 0:00:01
   --------------------------------- ------ 9.1/10.7 MB 3.9 MB/s eta 0:00:01
   ---------------------------------- ----- 9.3/10.7 MB 4.0 MB/s eta 0:00:01
   ----------------------------------- ---- 9.5/10.7 MB 4.0 MB/s eta 0:00:01
   ------------------------------------ --- 9.7/10.7 MB 4.0 MB/s eta 0:00:01
   ------------------------------------ --- 9.7/10.7 MB 4.0 MB/s eta 0:00:01
   ------------------------------------ --- 9.7/10.7 MB 3.8 MB/s eta 0:00:01
   ------------------------------------ --- 9.9/10.7 MB 3.8 MB/s eta 0:00:01
   ------------------------------------- -- 10.1/10.7 MB 3.8 MB/s eta 0:00:01
   ------------------------------------- -- 10.2/10.7 MB 3.8 MB/s eta 0:00:01
   -------------------------------------- - 10.4/10.7 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------  10.6/10.7 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------  10.7/10.7 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------  10.7/10.7 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------- 10.7/10.7 MB 3.8 MB/s eta 0:00:00
Downloading numpy-2.5.4-cp312-cp312-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.2/12.6 MB 4.6 MB/s eta 0:00:03
   - -------------------------------------- 0.4/12.6 MB 5.4 MB/s eta 0:00:03
   -- ------------------------------------- 0.6/12.6 MB 5.0 MB/s eta 0:00:03
   -- ------------------------------------- 0.8/12.6 MB 4.3 MB/s eta 0:00:03
   --- ------------------------------------ 1.0/12.6 MB 4.1 MB/s eta 0:00:03
   --- ------------------------------------ 1.1/12.6 MB 4.3 MB/s eta 0:00:03
   ---- ----------------------------------- 1.3/12.6 MB 4.4 MB/s eta 0:00:03
   ---- ----------------------------------- 1.5/12.6 MB 4.4 MB/s eta 0:00:03
   ----- ---------------------------------- 1.6/12.6 MB 4.3 MB/s eta 0:00:03
   ------ --------------------------------- 1.9/12.6 MB 4.5 MB/s eta 0:00:03
   ------ --------------------------------- 2.2/12.6 MB 4.6 MB/s eta 0:00:03
   ------- -------------------------------- 2.3/12.6 MB 4.6 MB/s eta 0:00:03
   ------- -------------------------------- 2.5/12.6 MB 4.5 MB/s eta 0:00:03
   -------- ------------------------------- 2.6/12.6 MB 4.5 MB/s eta 0:00:03
   --------- ------------------------------ 2.9/12.6 MB 4.6 MB/s eta 0:00:03
   --------- ------------------------------ 3.0/12.6 MB 4.5 MB/s eta 0:00:03
   ---------- ----------------------------- 3.2/12.6 MB 4.4 MB/s eta 0:00:03
   ---------- ----------------------------- 3.3/12.6 MB 4.4 MB/s eta 0:00:03
   ----------- ---------------------------- 3.5/12.6 MB 4.4 MB/s eta 0:00:03
   ----------- ---------------------------- 3.6/12.6 MB 4.3 MB/s eta 0:00:03
   ----------- ---------------------------- 3.7/12.6 MB 4.2 MB/s eta 0:00:03
   ------------ --------------------------- 3.9/12.6 MB 4.2 MB/s eta 0:00:03
   ------------ --------------------------- 4.0/12.6 MB 4.2 MB/s eta 0:00:03
   ------------- -------------------------- 4.2/12.6 MB 4.2 MB/s eta 0:00:03
   -------------- ------------------------- 4.5/12.6 MB 4.2 MB/s eta 0:00:02
   -------------- ------------------------- 4.5/12.6 MB 4.2 MB/s eta 0:00:02
   -------------- ------------------------- 4.7/12.6 MB 4.2 MB/s eta 0:00:02
   --------------- ------------------------ 4.8/12.6 MB 4.1 MB/s eta 0:00:02
   --------------- ------------------------ 5.0/12.6 MB 4.1 MB/s eta 0:00:02
   ---------------- ----------------------- 5.1/12.6 MB 4.1 MB/s eta 0:00:02
   ---------------- ----------------------- 5.1/12.6 MB 3.9 MB/s eta 0:00:02
   ---------------- ----------------------- 5.2/12.6 MB 3.9 MB/s eta 0:00:02
   ---------------- ----------------------- 5.3/12.6 MB 3.8 MB/s eta 0:00:02
   ----------------- ---------------------- 5.5/12.6 MB 3.8 MB/s eta 0:00:02
   ------------------ --------------------- 5.7/12.6 MB 3.9 MB/s eta 0:00:02
   ------------------ --------------------- 5.8/12.6 MB 3.9 MB/s eta 0:00:02
   ------------------- -------------------- 6.0/12.6 MB 3.9 MB/s eta 0:00:02
   ------------------- -------------------- 6.2/12.6 MB 3.9 MB/s eta 0:00:02
   -------------------- ------------------- 6.4/12.6 MB 3.9 MB/s eta 0:00:02
   --------------------- ------------------ 6.6/12.6 MB 4.0 MB/s eta 0:00:02
   --------------------- ------------------ 6.8/12.6 MB 3.9 MB/s eta 0:00:02
   ---------------------- ----------------- 7.0/12.6 MB 4.0 MB/s eta 0:00:02
   ---------------------- ----------------- 7.1/12.6 MB 4.0 MB/s eta 0:00:02
   ---------------------- ----------------- 7.2/12.6 MB 3.9 MB/s eta 0:00:02
   ----------------------- ---------------- 7.5/12.6 MB 3.9 MB/s eta 0:00:02
   ------------------------ --------------- 7.7/12.6 MB 3.9 MB/s eta 0:00:02
   ------------------------ --------------- 7.8/12.6 MB 3.9 MB/s eta 0:00:02
   ------------------------- -------------- 8.0/12.6 MB 3.9 MB/s eta 0:00:02
   -------------------------- ------------- 8.2/12.6 MB 4.0 MB/s eta 0:00:02
   -------------------------- ------------- 8.4/12.6 MB 4.0 MB/s eta 0:00:02
   --------------------------- ------------ 8.6/12.6 MB 4.0 MB/s eta 0:00:02
   --------------------------- ------------ 8.8/12.6 MB 4.0 MB/s eta 0:00:01
   ---------------------------- ----------- 8.8/12.6 MB 3.9 MB/s eta 0:00:01
   ---------------------------- ----------- 8.9/12.6 MB 3.9 MB/s eta 0:00:01
   ---------------------------- ----------- 9.1/12.6 MB 3.9 MB/s eta 0:00:01
   ----------------------------- ---------- 9.2/12.6 MB 3.9 MB/s eta 0:00:01
   ----------------------------- ---------- 9.4/12.6 MB 3.9 MB/s eta 0:00:01
   ------------------------------ --------- 9.6/12.6 MB 3.9 MB/s eta 0:00:01
   ------------------------------ --------- 9.7/12.6 MB 3.9 MB/s eta 0:00:01
   ------------------------------- -------- 9.8/12.6 MB 3.9 MB/s eta 0:00:01
   ------------------------------- -------- 10.0/12.6 MB 3.9 MB/s eta 0:00:01
   -------------------------------- ------- 10.2/12.6 MB 3.9 MB/s eta 0:00:01
   -------------------------------- ------- 10.3/12.6 MB 3.9 MB/s eta 0:00:01
   --------------------------------- ------ 10.5/12.6 MB 3.9 MB/s eta 0:00:01
   ---------------------------------- ----- 10.8/12.6 MB 3.9 MB/s eta 0:00:01
   ---------------------------------- ----- 11.0/12.6 MB 3.9 MB/s eta 0:00:01
   ----------------------------------- ---- 11.2/12.6 MB 3.9 MB/s eta 0:00:01
   ----------------------------------- ---- 11.3/12.6 MB 3.9 MB/s eta 0:00:01
   ------------------------------------ --- 11.5/12.6 MB 3.9 MB/s eta 0:00:01
   ------------------------------------- -- 11.6/12.6 MB 3.9 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.6 MB 3.9 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.6 MB 3.9 MB/s eta 0:00:01
   -------------------------------------- - 12.0/12.6 MB 3.8 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.6 MB 3.8 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.6 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.6 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 3.7 MB/s eta 0:00:00
Downloading matplotlib-3.11.2-cp312-cp312-win_amd64.whl (9.3 MB)
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
    --------------------------------------- 0.2/9.3 MB 4.5 MB/s eta 0:00:03
   - -------------------------------------- 0.4/9.3 MB 4.5 MB/s eta 0:00:03
   -- ------------------------------------- 0.5/9.3 MB 4.2 MB/s eta 0:00:03
   --- ------------------------------------ 0.7/9.3 MB 4.5 MB/s eta 0:00:02
   --- ------------------------------------ 0.8/9.3 MB 4.2 MB/s eta 0:00:03
   ---- ----------------------------------- 0.9/9.3 MB 3.7 MB/s eta 0:00:03
   ----- ---------------------------------- 1.2/9.3 MB 4.0 MB/s eta 0:00:03
   ----- ---------------------------------- 1.4/9.3 MB 4.1 MB/s eta 0:00:02
   ------ --------------------------------- 1.5/9.3 MB 4.1 MB/s eta 0:00:02
   ------- -------------------------------- 1.7/9.3 MB 4.1 MB/s eta 0:00:02
   -------- ------------------------------- 2.0/9.3 MB 4.1 MB/s eta 0:00:02
   --------- ------------------------------ 2.1/9.3 MB 4.2 MB/s eta 0:00:02
   --------- ------------------------------ 2.3/9.3 MB 4.2 MB/s eta 0:00:02
   ---------- ----------------------------- 2.5/9.3 MB 4.2 MB/s eta 0:00:02
   ----------- ---------------------------- 2.6/9.3 MB 4.2 MB/s eta 0:00:02
   ------------ --------------------------- 2.9/9.3 MB 4.3 MB/s eta 0:00:02
   ------------- -------------------------- 3.1/9.3 MB 4.3 MB/s eta 0:00:02
   ------------- -------------------------- 3.2/9.3 MB 4.2 MB/s eta 0:00:02
   -------------- ------------------------- 3.4/9.3 MB 4.2 MB/s eta 0:00:02
   --------------- ------------------------ 3.5/9.3 MB 4.3 MB/s eta 0:00:02
   --------------- ------------------------ 3.7/9.3 MB 4.1 MB/s eta 0:00:02
   ---------------- ----------------------- 3.8/9.3 MB 4.0 MB/s eta 0:00:02
   ---------------- ----------------------- 3.9/9.3 MB 3.9 MB/s eta 0:00:02
   ----------------- ---------------------- 4.1/9.3 MB 4.0 MB/s eta 0:00:02
   ------------------ --------------------- 4.4/9.3 MB 4.1 MB/s eta 0:00:02

  WARNING: The scripts f2py.exe and numpy-config.exe are installed in 'c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'c:\Users\Lenovo\AppData\Local\Programs\Python\Python312\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 23.2.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
import pandas as pd
import numpy as np
print(pd.__version__)

3.1.0

In [11]:
df = pd.read_csv("E:\SQL_Projects\employee-attrition-analysis\data\HR-Employee-Attrition.csv")
print(df.shape)
df.head()

(1470, 35)

<>:1: SyntaxWarning: invalid escape sequence '\S'
<>:1: SyntaxWarning: invalid escape sequence '\S'
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_7004\1640846075.py:1: SyntaxWarning: invalid escape sequence '\S'
  df = pd.read_csv("E:\SQL_Projects\employee-attrition-analysis\data\HR-Employee-Attrition.csv")

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   str
 2   BusinessTravel            1470 non-null   str
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   str
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   str
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   str
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   str
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   str
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   str
 22  OverTime                  1470 non-null   str
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), str(9)
memory usage: 402.1 KB

In [13]:
df["Attrition"].value_counts(normalize=True) * 100

Attrition
No     83.877551
Yes    16.122449
Name: proportion, dtype: float64

Baseline: 1,470 employees, 16.1% attrition (237 left, 1,233 stayed). The data is imbalanced (about 5:1), so accuracy alone will be misleading when we build the model.

In [14]:
print(df.isnull().sum().sum())
print(df.duplicated().sum())

0
0

In [15]:
for col in df.columns:
    if df[col].nunique() == 1:
        print(col, "->", df[col].unique())

EmployeeCount -> [1]
Over18 -> <StringArray>
['Y']
Length: 1, dtype: str
StandardHours -> [80]

In [16]:
df = df.drop(columns=["EmployeeCount", "StandardHours", "Over18", "EmployeeNumber"])
print(df.shape)

(1470, 31)

In [17]:
df.to_csv("../data/hr_attrition_clean.csv", index=False)

In [18]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,...,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,...,4,4,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,...,3,2,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,...,3,3,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,...,3,4,1,6,3,3,2,2,2,2

In [19]:
df["AttritionFlag"]= (df["Attrition"] == "Yes").astype(int)

In [20]:
df["AttritionFlag"].mean()

np.float64(0.16122448979591836)

Tenure band

In [21]:
df["TenureBand"] = pd.cut(
    df["YearsAtCompany"],bins=[-1, 2, 5, 10, 50],
    labels=["0-2 yrs","3-5 yrs","6-10 yrs","10+ yrs"]
)

Age Band

In [22]:
df["AgeBand"] = pd.cut(
    df["Age"],
    bins=[17,25,35,45,60],
    labels=["18-25", "26-35","36-45","46-60"]
)

Income band

In [23]:
df["IncomeBand"] = pd.qcut(
    df["MonthlyIncome"],
    q=4,
    labels=["Low", "Lower-Mid", "Upper-Mid", "High"]
)

In [24]:
df["LongPromotionGap"] = (df["YearsSinceLastPromotion"] >= 4).astype(int)

In [25]:
df[["AttritionFlag", "TenureBand", "AgeBand", "IncomeBand", "LongPromotionGap"]].head()

   AttritionFlag TenureBand AgeBand IncomeBand  LongPromotionGap
0              1   6-10 yrs   36-45  Upper-Mid                 0
1              0   6-10 yrs   46-60  Upper-Mid                 0
2              1    0-2 yrs   36-45        Low                 0
3              0   6-10 yrs   26-35        Low                 0
4              0    0-2 yrs   26-35  Lower-Mid                 0

In [26]:
df.to_csv("../data/hr_attrition_clean.csv", index=False)